accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from accounts import views

app_name = 'accounts'

urlpatterns = [
    path(
        'register/',
        views.RegisterUserView.as_view(),
        name='register-user'
    ),
    path(
        'verify/<str:uidb64>/<str:token>/',
        views.VerifyAccountView.as_view(),
        name='verify-account'
    ),

    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path(
        'reset-password/',
        views.PasswordResetView.as_view(),
        name='reset-password'
    ),
    path(
        'reset-password-confirm/<uidb64>/<token>/',
        views.PasswordResetConfirmView.as_view(),
        name='reset-password-confirm'
    ),

    path(
        'dashboard/change-password/',
        views.PasswordChangeView.as_view(),
        name='change-password'
    ),
    path(
        'dashboard/edit/',
        views.UserUpdateView.as_view(),
        name='user-update'
    ),
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
]

blog/urls.py
from django.urls import path

from blog import views

app_name = 'blog'

urlpatterns = [
    path(
        'bookmarks/',
        views.BookmarksView.as_view(),
        name='bookmarks'
    ),
    path(
        'my-posts/',
        views.MyPostListView.as_view(),
        name='my-post-list'
    ),
    path(
        'authors/<str:username>/',
        views.UserPostListView.as_view(),
        name='user-post-list'
    ),
    path(
        'categories/<slug:slug>/',
        views.CategoryPostListView.as_view(),
        name='category-post-list'
    ),
    path('posts/new/', views.PostCreateView.as_view(), name='post-create'),
    path(
        'posts/search/',
        views.SearchPostListView.as_view(),
        name='search-post-list'
    ),
    path(
        'posts/bookmark/',
        views.BookmarkPostView.as_view(),
        name='bookmark-post'
    ),
    path(
        'posts/<slug:slug>/comments/new/',
        views.CommentCreateView.as_view(),
        name='comment-create'
    ),
    path(
        'posts/<slug:slug>/delete/',
        views.PostDeleteView.as_view(),
        name='post-delete'
    ),
    path(
        'posts/<slug:slug>/edit/',
        views.PostUpdateView.as_view(),
        name='post-update'
    ),
    path(
        'posts/<slug:slug>/',
        views.PostDetailView.as_view(),
        name='post-detail'
    ),
    path(
        'tags/<slug:tag_slug>/',
        views.TagPostListView.as_view(),
        name='tag-post-list'
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('blog/', include('blog.urls', namespace='blog'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from core.views import IndexView

app_name = 'core'

urlpatterns = [
    path('', view=IndexView.as_view(), name='index')
]

blog/models.py
from django.conf import settings
from django.db import models
from django.db.models import Count, Q
from django.urls import reverse
from django.utils.text import slugify

from mptt.models import MPTTModel, TreeForeignKey


def post_media_directory(instance, filename):
    return f'blog/posts/{instance.id}/{filename}'


class Category(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.CharField(max_length=500, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'categories'
        ordering = ['title']

    def __str__(self):
        return self.title


class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        return super(Tag, self).save(*args, **kwargs)
    
    def get_top_tags(self):
        '''
        Get top tags based on published related posts
        '''
        published_posts_count = Count(
            'posts',
            filter=Q(posts__status=Post.POST_STATUS_PUBLISHED)
        )
        return Tag.objects.annotate(posts_count=published_posts_count) \
            .filter(posts_count__gt=0) \
            .order_by('-posts_count')[:8]


class PublishedPostManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset() \
            .select_related('user') \
            .prefetch_related('tags') \
            .filter(status=Post.POST_STATUS_PUBLISHED, is_active=True)


class Post(models.Model):
    POST_STATUS_DRAFT = 'draft'
    POST_STATUS_PUBLISHED = 'published'
    POST_STATUS = [
        (POST_STATUS_DRAFT, 'Draft'),
        (POST_STATUS_PUBLISHED, 'Published')
    ]

    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    content = models.TextField()
    image = models.ImageField(
        upload_to=post_media_directory,
        null=True,
        blank=True,
        default='blog/posts/default.png'
    )
    views = models.PositiveIntegerField(default=0)
    status = models.CharField(
        max_length=50,
        choices=POST_STATUS,
        default=POST_STATUS_DRAFT
    )
    is_active = models.BooleanField(verbose_name='active', default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name='posts'
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
        related_name='posts'
    )
    tags = models.ManyToManyField(Tag, blank=True, related_name='posts')
    bookmarks = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=True,
        related_name='bookmarks'
    )
    likes = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=True,
        related_name='likes'
    )

    objects = models.Manager()
    published = PublishedPostManager()

    class Meta:
        ordering = ['-created_at']
        permissions = [('olp_blog_change_post', 'OLP - Can change post')]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
        return super(Post, self).save(*args, **kwargs)

    def delete(self):
        self.is_active = False
        self.save()

    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs={'slug': self.slug})


class Comment(MPTTModel):
    COMMENT_STATUS_PENDING = 'pending'
    COMMENT_STATUS_APPROVED = 'approved'
    COMMENT_STATUS_NOT_APPROVED = 'not approved'
    COMMENT_STATUS = [
        (COMMENT_STATUS_PENDING, 'Pending'),
        (COMMENT_STATUS_APPROVED, 'Approved'),
        (COMMENT_STATUS_NOT_APPROVED, 'Not approved')
    ]

    content = models.TextField()
    status = models.CharField(
        max_length=50,
        choices=COMMENT_STATUS,
        default=COMMENT_STATUS_PENDING
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    parent = TreeForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='children'
    )

    class MPTTMeta:
        order_insertion_by = ['-created_at']

    def __str__(self):
        return f'Comment id={self.id}'

templates/includes/alert.html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </li>
        {% endfor %}
    </ul>
{% endif %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'core:index' %}">Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:index' %}">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Categories</a>
                    <ul class="dropdown-menu">
                        {% for category in categories %}
                            <li>
                                <a class="dropdown-item" href="{% url 'blog:category-post-list' slug=category.slug %}">
                                    {{ category.title }}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {{ request.user.get_full_name }}
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <img src="{{ request.user.image.url }}" alt="User Profile" class="user-profile-image--sm">
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'accounts:dashboard' %}">Dashboard</a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'blog:bookmarks' %}">Bookmarks</a>
                            </li>
                            {% if perms.blog.add_post %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'blog:post-create' %}">New post</a>
                                </li>
                            {% endif %}
                            {% if perms.blog.view_post %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'blog:my-post-list' %}">My Posts</a>
                                </li>
                            {% endif %}
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <a class="dropdown-item text-danger" href="{% url 'accounts:logout' %}">Sign out</a>
                            </li>
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">Sign in</a>
                    </li>
                {% endif %}
            </ul>
            <form action="{% url 'blog:search-post-list' %}" method="get" class="d-flex" role="search">
                <input class="form-control me-2" name="q" value="{{ query }}" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

templates/includes/pagination.html
{% if queryset.has_other_pages %}
    <nav class="my-5">
        <ul class="pagination justify-content-center">
            {% if queryset.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?{% if query %}q={{ query }}&{% endif %}page={{ queryset.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% else %}
                <li class="page-item">
                    <button class="page-link" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    </button>
                </li>
            {% endif %}

            {% for page in queryset.paginator.page_range %}
                {% if page == queryset.number %}
                    <li class="page-item active">
                        <button class="page-link">{{ page }}</button>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a href="?{% if query %}q={{ query }}&{% endif %}page={{ page }}" class="page-link">{{ page }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            {% if queryset.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?{% if query %}q={{ query }}&{% endif %}page={{ queryset.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% else %}
                <li class="page-item">
                    <button class="page-link"aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    </button>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}