accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from accounts import views

app_name = 'accounts'

urlpatterns = [
    path(
        'register/',
        views.RegisterUserView.as_view(),
        name='register-user'
    ),
    path(
        'verify/<str:uidb64>/<str:token>/',
        views.VerifyAccountView.as_view(),
        name='verify-account'
    ),

    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path(
        'reset-password/',
        views.PasswordResetView.as_view(),
        name='reset-password'
    ),
    path(
        'reset-password-confirm/<uidb64>/<token>/',
        views.PasswordResetConfirmView.as_view(),
        name='reset-password-confirm'
    ),

    path(
        'dashboard/change-password/',
        views.PasswordChangeView.as_view(),
        name='change-password'
    ),
    path(
        'dashboard/edit/',
        views.UserUpdateView.as_view(),
        name='user-update'
    ),
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
]

blog/urls.py
from django.urls import path

from blog import views

app_name = 'blog'

urlpatterns = [
    path(
        'bookmarks/',
        views.BookmarksView.as_view(),
        name='bookmarks'
    ),
    path(
        'my-posts/',
        views.MyPostListView.as_view(),
        name='my-post-list'
    ),
    path(
        'authors/<str:username>/',
        views.UserPostListView.as_view(),
        name='user-post-list'
    ),
    path(
        'categories/<slug:slug>/',
        views.CategoryPostListView.as_view(),
        name='category-post-list'
    ),
    path('posts/new/', views.PostCreateView.as_view(), name='post-create'),
    path(
        'posts/search/',
        views.SearchPostListView.as_view(),
        name='search-post-list'
    ),
    path(
        'posts/bookmark/',
        views.BookmarkPostView.as_view(),
        name='bookmark-post'
    ),
    path(
        'posts/<slug:slug>/comments/new/',
        views.CommentCreateView.as_view(),
        name='comment-create'
    ),
    path(
        'posts/<slug:slug>/delete/',
        views.PostDeleteView.as_view(),
        name='post-delete'
    ),
    path(
        'posts/<slug:slug>/edit/',
        views.PostUpdateView.as_view(),
        name='post-update'
    ),
    path(
        'posts/<slug:slug>/',
        views.PostDetailView.as_view(),
        name='post-detail'
    ),
    path(
        'tags/<slug:tag_slug>/',
        views.TagPostListView.as_view(),
        name='tag-post-list'
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('blog/', include('blog.urls', namespace='blog'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.conf import settings
from django.db import models
from django.db.models import Count, Q
from django.urls import reverse
from django.utils.text import slugify

from mptt.models import MPTTModel, TreeForeignKey


def post_media_directory(instance, filename):
    return f'blog/posts/{instance.id}/{filename}'


class Category(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.CharField(max_length=500, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'categories'
        ordering = ['title']

    def __str__(self):
        return self.title


class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        return super(Tag, self).save(*args, **kwargs)
    
    def get_top_tags(self):
        '''
        Get top tags based on published related posts
        '''
        published_posts_count = Count(
            'posts',
            filter=Q(posts__status=Post.POST_STATUS_PUBLISHED)
        )
        return Tag.objects.annotate(posts_count=published_posts_count) \
            .filter(posts_count__gt=0) \
            .order_by('-posts_count')[:8]


class PublishedPostManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset() \
            .select_related('user') \
            .prefetch_related('tags') \
            .filter(status=Post.POST_STATUS_PUBLISHED, is_active=True)


class Post(models.Model):
    POST_STATUS_DRAFT = 'draft'
    POST_STATUS_PUBLISHED = 'published'
    POST_STATUS = [
        (POST_STATUS_DRAFT, 'Draft'),
        (POST_STATUS_PUBLISHED, 'Published')
    ]

    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    content = models.TextField()
    image = models.ImageField(
        upload_to=post_media_directory,
        null=True,
        blank=True,
        default='blog/posts/default.png'
    )
    views = models.PositiveIntegerField(default=0)
    status = models.CharField(
        max_length=50,
        choices=POST_STATUS,
        default=POST_STATUS_DRAFT
    )
    is_active = models.BooleanField(verbose_name='active', default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name='posts'
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
        related_name='posts'
    )
    tags = models.ManyToManyField(Tag, blank=True, related_name='posts')
    bookmarks = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=True,
        related_name='bookmarks'
    )
    likes = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=True,
        related_name='likes'
    )

    objects = models.Manager()
    published = PublishedPostManager()

    class Meta:
        ordering = ['-created_at']
        permissions = [('olp_blog_change_post', 'OLP - Can change post')]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
        return super(Post, self).save(*args, **kwargs)

    def delete(self):
        self.is_active = False
        self.save()

    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs={'slug': self.slug})


class Comment(MPTTModel):
    COMMENT_STATUS_PENDING = 'pending'
    COMMENT_STATUS_APPROVED = 'approved'
    COMMENT_STATUS_NOT_APPROVED = 'not approved'
    COMMENT_STATUS = [
        (COMMENT_STATUS_PENDING, 'Pending'),
        (COMMENT_STATUS_APPROVED, 'Approved'),
        (COMMENT_STATUS_NOT_APPROVED, 'Not approved')
    ]

    content = models.TextField()
    status = models.CharField(
        max_length=50,
        choices=COMMENT_STATUS,
        default=COMMENT_STATUS_PENDING
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    parent = TreeForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='children'
    )

    class MPTTMeta:
        order_insertion_by = ['-created_at']

    def __str__(self):
        return f'Comment id={self.id}'

blog/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from mptt.forms import TreeNodeChoiceField

from blog.models import Comment, Post
from core.forms import BootstrapyForm


class CommentForm(forms.ModelForm, BootstrapyForm):
    parent = TreeNodeChoiceField(queryset=Comment.objects.all())

    class Meta:
        model = Comment
        fields = ['parent', 'content']

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['parent'].required = False
        self.fields['content'].widget.attrs.update(
            {'placeholder': _('Write your comment')}
        )


class PostForm(forms.ModelForm, BootstrapyForm):
    class Meta:
        model = Post
        fields = ['category', 'title', 'content', 'image', 'status', 'tags']

blog/templates/blog/bookmarks.html
{% extends 'base.html' %}

{% block title %}
    Bookmarks
{% endblock title %}

{% block content %}
    <div class="container">
        {% include "includes/alert.html" %}
        <section class="my-5">
            <div class="mb-4">
                <h1>Bookmarks</h1>
                <p class="lead">
                    {{ posts.count }} Post{{ posts.count|pluralize }}
                </p>
            </div>
            <div class="row">
                {% for post in posts %}
                    <div class="col-12 col-md-6 col-lg-4">
                        {% include "blog/includes/post.html" %}
                    </div>
                {% empty %}
                    <h2 class="h4">You have no bookmarks.</h2>
                {% endfor %}
            </div>
            {% include "includes/pagination.html" with queryset=page_obj %}
        </section>
    </div>
{% endblock content %}

blog/templates/blog/category_post_list.html
{% extends 'base.html' %}

{% block title %}
    {{ category.title }} Posts
{% endblock title %}

{% block content %}
    <div class="container">
        <section class="my-5">
            <h1 class="mt-3">
                '{{ category.title }}' Posts
            </h1>
            <div class="row">
                {% for post in posts %}
                    <div class="col-12 col-md-6 col-lg-4">
                        {% include "blog/includes/post.html" %}
                    </div>
                {% endfor %}
            </div>
            {% include "includes/pagination.html" with queryset=page_obj %}
        </section>
    </div>
{% endblock content %}

blog/templates/blog/my_post_list.html
{% extends 'base.html' %}

{% block title %}
    My Posts
{% endblock title %}

{% block content %}
    <div class="container">
        {% include "includes/alert.html" %}
        <h1 class="mt-3">
            My Posts
        </h1>
        <p class="lead">
            {{ posts_count }} Post{{ posts_count|pluralize }} found
        </p>
        <section class="my-5">
            <div class="row">
                {% for post in posts %}
                    <div class="col-12 col-md-6 col-lg-4">
                        {% include "blog/includes/private_post.html" %}
                    </div>
                {% empty %}
                    <h2 class="h4">You have no posts.</h2>
                {% endfor %}
            </div>
        </section>
    </div>
{% endblock content %}

blog/templates/blog/post_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    Confirm delete
{% endblock title %}

{% block content %}
    <div class="container">
        <form method="post" class="form my-5">
            {% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            {{ form }}
            <button class="btn btn-danger">Confirm</button>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/post_create.html
{% extends 'base.html' %}

{% block title %}
    New post
{% endblock title %}

{% block content %}
    <main>
        <div class="container">
            <form action="" method="post" class="form my-5">
                {% csrf_token %}

                {% if form.non_field_errors %}
                    <ul class="form-errors">
                        {% for error in form.non_field_errors %}
                            <li>
                                {{ error }}
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}

                {% for field in form %}
                    <div class="mb-3">
                        {{ field.label_tag }}
                        {{ field }}
                        {% if field.errors %}
                            <ul>
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </div>
                {% endfor %}

                <button class="btn btn-primary">Submit</button>
            </form>
        </div>
    </main>
{% endblock content %}

blog/templates/blog/post_create_update.html
{% extends 'base.html' %}

{% block title %}
    {% if post %}
        Edit post
    {% else %}
        New Post
    {% endif %}
{% endblock title %}

{% block content %}
    <main>
        <div class="container">
            <div class="form-wrapper form-wrapper--xlg">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
    
                    {% if form.non_field_errors %}
                        <ul class="form-errors">
                            {% for error in form.non_field_errors %}
                                <li>
                                    {{ error }}
                                </li>
                            {% endfor %}
                        </ul>
                    {% endif %}
    
                    {% for field in form %}
                        <div class="mb-3">
                            {{ field.label_tag }}
                            {{ field }}
                            {% if field.errors %}
                                <ul>
                                    {% for error in field.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                    {% endfor %}
    
                    <button class="btn btn-primary d-block w-100">Submit</button>
                </form>
            </div>
        </div>
    </main>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% load static %}
{% load guardian_tags %}
{% load mptt_tags %}

{% block title %}
    {{ post.title }}
{% endblock title %}

{% block content %}
    <div class="container">
        {% include "includes/alert.html" %}
        <section class="my-5">
            <h1 class="mb-3">{{ post.title }}</h1>
            <div class="row">
                <!-- 1st column -->
                <div class="col-12 col-md-9">
                    <div>
                        {% if post.image %}
                            <img src="{{ post.image.url }}" alt="Post Image">
                        {% else %}
                            <img src="{% static 'images/no_image_available.png' %}" alt="Post Image">
                        {% endif %}
                    </div>
                    {% if is_bookmarkable %}
                        <div class="mt-2">
                            {% if request.user.is_authenticated %}
                                {% if is_bookmarked %}
                                    <button class="btn-bookmark fs-3" data-pk="{{ post.pk }}" data-url="{% url 'blog:bookmark-post' %}">
                                        <i class="bi bi-bookmark-check-fill"></i>
                                    </button>
                                {% else %}
                                    <button class="btn-bookmark fs-3" data-pk="{{ post.pk }}" data-url="{% url 'blog:bookmark-post' %}">
                                        <i class="bi bi-bookmark"></i>
                                    </button>
                                {% endif %}
                            {% else %}
                                <a href="{% url 'accounts:login' %}?next={{ request.path }}" class="fs-3">
                                    <i class="bi bi-bookmark"></i>
                                </a>
                            {% endif %}
                        </div>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                        <ul class="d-flex gap-1 p-0">
                            {% if perms.blog.change_post %}
                                {% if "olp_blog_change_post" in post_perms %}
                                    <li>
                                        <a href="{% url 'blog:post-update' slug=post.slug %}" class="btn btn-warning">Edit post</a>
                                    </li>
                                {% endif %}
                            {% endif %}
                            {% if perms.blog.delete_post %}
                                {% if "olp_blog_change_post" in post_perms %}
                                    <li>
                                        <a href="{% url 'blog:post-delete' slug=post.slug %}" class="btn btn-danger">Delete post</a>
                                    </li>
                                {% endif %}
                            {% endif %}
                        </ul>
                    {% endif %}
                    <h2 class="h5 mt-3">
                        <a href="{% url 'blog:user-post-list' username=post.user.username %}">
                            Author: {{ post.user.get_full_name }}
                        </a>
                    </h2>
                    <p>
                        Created: {{ post.created_at|date:"M d, Y" }}
                    </p>
                    <p>
                        Views: {{ post.views }}
                    </p>
                    {% if post.user == request.user %}
                        <p>
                            Status: <span class="text-primary">{{ post.status|title }}</span>
                        </p>
                    {% endif %}
                    {% if post_tags %}
                        <div>
                            {% for tag in post_tags %}
                                {% include "blog/includes/tag.html" %}
                            {% endfor %}
                        </div>
                    {% endif %}
                    <p class="mt-3">
                        {{ post.content|linebreaksbr }}
                    </p>
                    <hr>
                    {% if request.user.is_authenticated %}
                        <div>
                            <h3>Make a new comment</h3>
                            <form action="{% url 'blog:comment-create' slug=post.slug %}" method="post">
                                {% csrf_token %}
                                {% if form.non_field_errors %}
                                    <ul class="form-errors">
                                        {% for error in form.non_field_errors %}
                                            <li>
                                                {{ error }}
                                            </li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                                <div class="mb-3">
                                    {{ form.content }}
                                    {% if form.content.errors %}
                                        <ul>
                                            {% for error in form.content.errors %}
                                                <li>{{ error }}</li>
                                            {% endfor %}
                                        </ul>
                                    {% endif %}
                                </div>
    
                                <button class="btn btn-primary">Submit</button>
                            </form>
                        </div>
                    {% else %}
                        <p class="text-dark">
                            You must
                            <a href="{% url 'accounts:login' %}?next={{ request.path }}" class="text-primary">
                                sign in
                            </a>
                            to add a comment.
                        </p>
                    {% endif %}
                    {% if post_comments %}
                        <div class="mt-4">
                            <p class="lead">
                                <span class="fw-bold">{{ post_comments_count }}</span>
                                comment{{ post_comments_count|pluralize }}
                            </p>
                            {% recursetree post_comments %}
                                <div class="mb-3">
                                    <div class="border border-light-subtle rounded p-3" id="comment-{{ node.id }}">
                                        <div>
                                            <p class="fw-bold mb-1">
                                                {{ node.user.get_full_name }}
                                            </p>
                                            <p class="mb-3">
                                                {{ node.created_at|date:"M d, Y" }}
                                            </p>
                                        </div>
                                        <div class="w-100">
                                            <p class="text-justify comment-text mb-0">
                                                {{ node.content|linebreaksbr }}
                                            </p>
                                        </div>
                                        {% if node.user != request.user %}
                                            <div class="text-end">
                                                <button class="btn-reply text-primary" onclick="showReplyForm({{ node.id }})">Reply</button>
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>
                                {% if not node.is_leaf_node %}
                                    <div class="comment-reply">
                                        {{ children }}
                                    </div>
                                {% endif %}
                            {% endrecursetree %}
                        </div>
                    {% endif %}
                </div>
                <!-- 2nd column -->
                <div class="col-12 col-md-3">
                    <div>
                        <h3>Related Posts</h3>
                        <hr>
                        {% for post in related_posts %}
                            <div class="mb-4">
                                <h4>{{ post.title|truncatewords:6 }}</h4>
                                <a href="{{ post.get_absolute_url }}" class="text-primary">Read more</a>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="mt-5">
                        <h3>Top Authors</h3>
                        <hr>
                        {% for user in top_users %}
                            <div class="mb-4">
                                <h4>{{ user.get_full_name|truncatewords:2 }}</h4>
                                <a href="{% url 'blog:user-post-list' username=user.username %}" class="text-primary">Show posts</a>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="mt-5">
                        <h3>Top Tags</h3>
                        <hr>
                        {% for tag in top_tags %}
                            {% include "blog/includes/tag.html" %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </section>
    </div>

    <script>
        function showReplyForm(nodeId) {
            if (document.contains(document.querySelector(".form-reply"))) {
                document.querySelector(".form-reply").remove();
            }
            let commentId = `comment-${nodeId}`;
            let comment = document.querySelector(`#${commentId}`);
            comment.insertAdjacentHTML(
                "afterend",
                `<div class="form-reply mt-3">
                    <h3>Reply</h3>
                    <form action="{% url 'blog:comment-create' slug=post.slug %}" method="post">
                        {% csrf_token %}
                        <select name="parent" class="d-none" required id="id_parent">
                            <option value="${nodeId}" selected></option>
                        </select>
                        <div class="mb-3">
                            <textarea name="content" cols="40" rows="10" class="form-control" placeholder="Write your comment" required="" id="id_content"></textarea>
                        </div>
                        <button class="btn btn-primary">Submit</button>
                    </form>
                </div>`
            )
        }
    </script>
{% endblock content %}

blog/templates/blog/search_post_list.html
{% extends 'base.html' %} 

{% block title %}
    Search Posts
{% endblock title %}

{% block content %}
    <div class="container">
        <h1 class="mt-3">Search Result</h1>
        <p class="lead">
            {{ posts_count }} Post{{ posts_count|pluralize }} found
        </p>
        <section class="my-5">
            <div class="row">
                {% for post in posts %}
                    <div class="col-12 col-md-6 col-lg-4">
                        {% include "blog/includes/post.html" %}
                    </div>
                {% endfor %}
                {% include "includes/pagination.html" with queryset=page_obj %}
            </div>
        </section>
    </div>
{% endblock content %}

blog/templates/blog/search_posts.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1 class="mt-3">Search Result</h1>

        <section class="my-5">
            <div class="row">
                {% for post in posts %}
                    <div class="col-12 col-md-6 col-lg-4">
                        {% include "blog/includes/post.html" %}
                    </div>
                {% endfor %}
            </div>
        </section>
    </div>
{% endblock content %}

blog/templates/blog/tag_post_list.html
{% extends 'base.html' %}

{% block title %}
    {{ tag.name }}
{% endblock title %}

{% block content %}
    <div class="container">
        <section class="my-5">
            <h1 class="mt-3">{{ tag.name }}</h1>
            <p class="lead">
                {{ tag_posts_count }} Post{{ tag_posts_count|pluralize }} found
            </p>
            <div class="row">
                <div class="col-12 col-lg-9">
                    <div class="row">
                        {% for post in tag_posts %}
                            <div class="col-12 col-md-6">
                                {% include "blog/includes/post.html" %}
                            </div>
                        {% endfor %}
                        {% include "includes/pagination.html" with queryset=page_obj %}
                    </div>
                </div>
                <div class="col-12 col-lg-3">
                    <div>
                        <h3>Top Tags</h3>
                        <hr>
                        {% for tag in top_tags %}
                            {% include "blog/includes/tag.html" %}
                        {% endfor %}
                    </div>
                    <div class="mt-5">
                        <h3>Other Tags</h3>
                        <hr>
                        {% for tag in other_tags %}
                            {% include "blog/includes/tag.html" %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock content %}

blog/templates/blog/user_post_list.html
{% extends 'base.html' %}

{% block title %}
    {{ user.get_full_name }} Posts
{% endblock title %}

{% block content %}
    <div class="container">
        <section class="my-5">
            <h1 class="mt-3">{{ user.get_full_name }}</h1>
            <p class="lead">
                {{ user_posts_count }} Post{{ user_posts_count|pluralize }} found
            </p>
            <div class="row">
                <div class="col-12 col-lg-9 mb-4">
                    <div class="row">
                        {% for post in user_posts %}
                            <div class="col-12 col-md-6">
                                {% include "blog/includes/post.html" %}
                            </div>
                        {% endfor %}
                        {% include "includes/pagination.html" with queryset=page_obj %}
                    </div>
                </div>
                <div class="col-12 col-lg-3">
                    <div>
                        <h3>Top Users</h3>
                        <hr>
                        {% for user in top_users %}
                            <div class="mb-4">
                                <h4>{{ user.get_full_name|truncatewords:2 }}</h4>
                                <a href="{% url 'blog:user-post-list' username=user.username %}" class="text-primary">Show posts</a>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="mt-5">
                        <h3>Other Users</h3>
                        <hr>
                        {% for user in other_users %}
                            <div class="mb-4">
                                <h4>{{ user.get_full_name|truncatewords:2 }}</h4>
                                <a href="{% url 'blog:user-post-list' username=user.username %}" class="text-primary">Show posts</a>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock content %}