accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from accounts import views

app_name = 'accounts'

urlpatterns = [
    path(
        'register/',
        views.RegisterUserView.as_view(),
        name='register-user'
    ),
    path(
        'verify/<str:uidb64>/<str:token>/',
        views.VerifyAccountView.as_view(),
        name='verify-account'
    ),

    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path(
        'reset-password/',
        views.PasswordResetView.as_view(),
        name='reset-password'
    ),
    path(
        'reset-password-confirm/<uidb64>/<token>/',
        views.PasswordResetConfirmView.as_view(),
        name='reset-password-confirm'
    ),

    path(
        'dashboard/change-password/',
        views.PasswordChangeView.as_view(),
        name='change-password'
    ),
    path(
        'dashboard/edit/',
        views.UserUpdateView.as_view(),
        name='user-update'
    ),
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
]

blog/urls.py
from django.urls import path

from blog import views

app_name = 'blog'

urlpatterns = [
    path(
        'bookmarks/',
        views.BookmarksView.as_view(),
        name='bookmarks'
    ),
    path(
        'my-posts/',
        views.MyPostListView.as_view(),
        name='my-post-list'
    ),
    path(
        'authors/<str:username>/',
        views.UserPostListView.as_view(),
        name='user-post-list'
    ),
    path(
        'categories/<slug:slug>/',
        views.CategoryPostListView.as_view(),
        name='category-post-list'
    ),
    path('posts/new/', views.PostCreateView.as_view(), name='post-create'),
    path(
        'posts/search/',
        views.SearchPostListView.as_view(),
        name='search-post-list'
    ),
    path(
        'posts/bookmark/',
        views.BookmarkPostView.as_view(),
        name='bookmark-post'
    ),
    path(
        'posts/<slug:slug>/comments/new/',
        views.CommentCreateView.as_view(),
        name='comment-create'
    ),
    path(
        'posts/<slug:slug>/delete/',
        views.PostDeleteView.as_view(),
        name='post-delete'
    ),
    path(
        'posts/<slug:slug>/edit/',
        views.PostUpdateView.as_view(),
        name='post-update'
    ),
    path(
        'posts/<slug:slug>/',
        views.PostDetailView.as_view(),
        name='post-detail'
    ),
    path(
        'tags/<slug:tag_slug>/',
        views.TagPostListView.as_view(),
        name='tag-post-list'
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('blog/', include('blog.urls', namespace='blog'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin
)
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from guardian.mixins import GuardianUserMixin


def user_media_directory(instance, filename):
    return f'accounts/users/{instance.id}/{filename}'


class UserManager(BaseUserManager):
    def create_user(
        self,
        email,
        username,
        first_name,
        last_name,
        password=None,
        **extra_fields
    ):
        if not email:
            raise ValueError('Users must have an email address.')

        if not username:
            raise ValueError('Users must have an username.')

        if not first_name:
            raise ValueError('Users must have a first_name.')

        if not last_name:
            raise ValueError('Users must have a last_name.')

        email = self.normalize_email(email)
        user = self.model(
            email=email,
            username=username,
            first_name=first_name,
            last_name=last_name,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(
        self,
        email,
        username,
        first_name,
        last_name,
        password=None,
        **extra_fields
    ):
        user = self.create_user(
            email,
            username,
            first_name,
            last_name,
            password,
            **extra_fields
        )
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin, GuardianUserMixin):
    username_validator = UnicodeUsernameValidator()

    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
        error_messages={
            'unique': _('A user with that email address already exists.')
        }
    )
    username = models.CharField(
        max_length=150,
        unique=True,
        validators=[username_validator],
        help_text=_(
            '150 characters or fewer. Letters, digits and @/./+/-/_ only.'
        ),
        error_messages={
            'unique': _('A user with that username already exists.')
        }
    )
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    image = models.ImageField(
        upload_to=user_media_directory,
        null=True,
        blank=True,
        default='accounts/users/default.svg'
    )
    bio = models.CharField(max_length=500, blank=True)
    is_active = models.BooleanField(
        verbose_name='active',
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        )
    )
    is_staff = models.BooleanField(
        verbose_name='staff status',
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'
        )
    )
    date_joined = models.DateTimeField(default=timezone.now)
    last_login = models.DateTimeField(blank=True, null=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def __str__(self):
        return self.email

    def get_full_name(self):
        return f'{self.first_name} {self.last_name}'

    def get_short_name(self):
        return self.first_name

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import (
    AuthenticationForm,
    BaseUserCreationForm,
    UserChangeForm as BaseUserChangeForm,
    PasswordChangeForm as BasePasswordChangeForm,
    PasswordResetForm as BasePasswordResetForm,
    SetPasswordForm as BaseSetPasswordForm
)
from django.utils.translation import gettext_lazy as _

from core.forms import BootstrapyForm

user_model = get_user_model()


class RegisterUserForm(BaseUserCreationForm, BootstrapyForm):
    error_messages = {
        'password_mismatch': _('Make sure your passwords match.'),
    }

    class Meta:
        model = user_model
        fields = [
            'email', 'username', 'first_name',
            'last_name', 'password1', 'password2'
        ]


class LoginForm(AuthenticationForm, BootstrapyForm):
    error_messages = {
        'invalid_login': _(
            'Please enter a correct %(username)s and password.'
        ),
    }

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'placeholder': _('Email address')
        })
        self.fields['password'].widget.attrs.update({
            'placeholder': _('Password')
        })


class UserChangeForm(BaseUserChangeForm, BootstrapyForm):
    class Meta:
        model = user_model
        fields = [
            'email', 'username', 'first_name',
            'last_name', 'image', 'bio'
        ]
        widgets = {
            'bio': forms.Textarea(attrs={'rows': 5})
        }


class PasswordChangeForm(BasePasswordChangeForm, BootstrapyForm):
    pass


class PasswordResetForm(BasePasswordResetForm, BootstrapyForm):
    pass


class SetPasswordForm(BaseSetPasswordForm, BootstrapyForm):
    pass

accounts/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Group
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import (
    LoginView as BaseLoginView,
    PasswordChangeView as BasePasswordChangeView,
    PasswordResetView as BasePasswordResetView,
    PasswordResetConfirmView as BasePasswordResetConfirmView
)
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.http import urlsafe_base64_decode
from django.utils.translation import gettext_lazy as _
from django.views.generic.base import TemplateView, RedirectView
from django.views.generic.edit import FormView, UpdateView

from accounts import forms
from accounts.utilities import send_verification_email


class RegisterUserView(SuccessMessageMixin, FormView):
    model = get_user_model()
    form_class = forms.RegisterUserForm
    template_name = 'accounts/registration/register_user.html'
    success_url = reverse_lazy('accounts:login')
    success_message = _('The verification link has been sent to your email.')

    def dispatch(self, request, *args, **kwargs):
        '''
        Prevent authenticated user to access register URL.
        '''
        if request.user.is_authenticated:
            return redirect('accounts:dashboard')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        email_subject = 'Account Verification'
        email_template = 'accounts/registration/verification_email.html'
        send_verification_email(
            self.request,
            user,
            email_subject,
            email_template
        )

        return super().form_valid(form)


class VerifyAccountView(RedirectView):
    url = reverse_lazy('accounts:login')

    def get_redirect_url(self, *args, **kwargs):
        try:
            user_id = urlsafe_base64_decode(self.kwargs['uidb64']).decode()
            user = get_user_model().objects.get(id=user_id)
        except (TypeError, ValueError, OverflowError, get_user_model().DoesNotExist):
            user = None

        if (
            (user is not None) and
            default_token_generator.check_token(user, self.kwargs['token'])
        ):
            user.is_active = True
            user.save()

            # Add user to group
            group = get_object_or_404(Group, name='Blog - Post Managers')
            group.user_set.add(user)

            messages.success(
                self.request,
                _('Your account has been successfully verified.')
            )
        else:
            messages.error(self.request, _('The link has been expired!'))
        return super().get_redirect_url(*args, **kwargs)


class LoginView(BaseLoginView):
    form_class = forms.LoginForm
    template_name = 'accounts/login.html'
    redirect_authenticated_user = True


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = get_user_model()
    form_class = forms.UserChangeForm
    template_name = 'accounts/user_update.html'
    success_url = reverse_lazy('accounts:dashboard')
    success_message = _('Your profile has been successfully edited.')

    def get_object(self, queryset=None):
        return self.request.user


class PasswordChangeView(SuccessMessageMixin, BasePasswordChangeView):
    form_class = forms.PasswordChangeForm
    template_name = 'accounts/password/change_password.html'
    success_url = reverse_lazy('accounts:dashboard')
    success_message = _('Your password has been successfully changed.')


class PasswordResetView(SuccessMessageMixin, BasePasswordResetView):
    form_class = forms.PasswordResetForm
    template_name = 'accounts/password/reset_password.html'
    success_url = reverse_lazy('accounts:login')
    email_template_name = 'accounts/password/reset_password_email.html'
    subject_template_name = 'accounts/password/reset_password_subject.txt'
    success_message = _('Password reset link was sent to your email.')


class PasswordResetConfirmView(
    SuccessMessageMixin,
    BasePasswordResetConfirmView
):
    form_class = forms.SetPasswordForm
    template_name = 'accounts/password/reset_password_confirm.html'
    success_url = reverse_lazy('accounts:login')
    success_message = _('Your password has been successfully reset.')


class Dashboard(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/dashboard.html'

accounts/templates/accounts/password/change_password.html
{% extends 'base.html' %}

{% block title %}
    Change password
{% endblock title %}

{% block content %}
    <main>
        <div class="container">
            <div class="form-wrapper">
                <form action="{% url 'accounts:change-password' %}" method="post">
                    {% csrf_token %}
    
                    {% if form.non_field_errors %}
                        <ul class="form-errors">
                            {% for error in form.non_field_errors %}
                                <li>
                                    {{ error }}
                                </li>
                            {% endfor %}
                        </ul>
                    {% endif %}
    
                    <div class="mb-3">
                        {{ form.old_password.label_tag }}
                        {{ form.old_password }}
                        {% if form.old_password.errors %}
                            <ul>
                                {% for error in form.old_password.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </div>
    
                    <div class="mb-3">
                        {{ form.new_password1.label_tag }}
                        {{ form.new_password1 }}
                        {% if form.new_password1.errors %}
                            <ul>
                                {% for error in form.new_password1.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </div>
    
                    <div class="mb-3">
                        {{ form.new_password2.label_tag }}
                        {{ form.new_password2 }}
                        {% if form.new_password2.errors %}
                            <ul>
                                {% for error in form.new_password2.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </div>
                    <button class="btn btn-primary d-block w-100">Change password</button>
                </form>
            </div>
        </div>
    </main>    
{% endblock content %}

accounts/templates/accounts/password/reset_password.html
{% extends 'base.html' %}

{% block title %}
    Reset password
{% endblock title %}

{% block content %}
    <main>
        <div class="container">
            <div class="form-wrapper">
                <form action="{% url 'accounts:reset-password' %}" method="post">
                    {% csrf_token %}
    
                    {% if form.non_field_errors %}
                        <ul class="form-errors">
                            {% for error in form.non_field_errors %}
                                <li>
                                    {{ error }}
                                </li>
                            {% endfor %}
                        </ul>
                    {% endif %}
    
                    <div class="mb-3">
                        {{ form.email.label_tag }}
                        {{ form.email }}
                        {% if form.email.errors %}
                            <ul>
                                {% for error in form.email.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </div>
                    <div class="text-center">
                        <button class="btn btn-primary d-block w-100">Request reset link</button>
                    </div>
                </form>
            </div>
        </div>
    </main>    
{% endblock content %}

accounts/templates/accounts/password/reset_password_confirm.html
{% extends 'base.html' %}

{% block title %}
    Reset password
{% endblock title %}

{% block content %}
    <main>
        <div class="container">
            <div class="form-wrapper">
                <form action="" method="post">
                    {% csrf_token %}
    
                    {% if form.non_field_errors %}
                        <ul class="form-errors">
                            {% for error in form.non_field_errors %}
                                <li>
                                    {{ error }}
                                </li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    
                    {% for field in form %}
                        <div class="mb-3">
                            {{ field.label_tag }}
                            {{ field }}
                            {% if field.errors %}
                                <ul>
                                    {% for error in field.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                    {% endfor %}
    
                    <button class="btn btn-primary">Chnage password</button>
                </form>
            </div>
        </div>
    </main>    
{% endblock content %}

accounts/templates/accounts/password/reset_password_email.html
{% autoescape off %}
<<<<<<< HEAD
<<<<<<< HEAD
Hi {{ user.get_full_name }}
=======
Hi {{ user.get_full_name }},
>>>>>>> feature
=======
Hi {{ user.get_full_name }},
>>>>>>> feature

We're sending you this email because you requested a password reset for your user account at {{ site_name }}.
Please go to the following page and choose a new password:

{{ protocol }}://{{ domain }}{% url 'accounts:reset-password-confirm' uidb64=uid token=token %}

If you didn't request a password reset, you can ignore this email. Your password will not be changed.
{% endautoescape %}